channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - snakemake>=6
  - biopython>=1.76
  - blast>=2.9.0
  - r-base>=4
  - r-conflicted
  - r-getopt>=1.20.3
  - r-argparser>=0.4
  - r-futile.logger>=1.4.3
  - r-glue>=1.3.1
  - r-plyr>=1.8.4
  - r-dplyr>=1.0.5
  - r-tibble>=2.1.1
  - r-reshape2>=1.4.3
  - r-rcolorbrewer>=1.1_2
  - r-ggplot2>=3.1.1
  - r-ape>=5.3
  - r-maps>=3.3.0
  - r-phytools>=0.6_99
  - r-tidytree>=0.3.1
  - bioconductor-treeio>=1.10.0
  - bioconductor-ggtree>=3.0.0
  - r-gridextra>=2.3
  - r-egg>=0.4.5
