channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=6
  - biopython>=1.76,<=1.79
  - blast>=2.9,<=2.12
  - r-base>=4.0,<=4.2
  - r-codetools
  - r-conflicted
  - r-getopt=1.20
  - r-argparser=0.7
  - r-futile.logger=1.4
  - r-glue=1
  - r-plyr=1.8
  - r-dplyr>=1.0.5,<=1.0.7
  - r-tibble=3.1
  - r-reshape2=1.4
  - r-rcolorbrewer=1.1_2
  - r-ggplot2=3
  - r-ape>=5.3,<=5.5
  - r-maps=3.3
  - r-phytools>=0.6_99,<=0.7_80
  - r-tidytree=0.3
  - bioconductor-treeio>=1.10,<=1.17
  - bioconductor-ggtree=3.0
  - r-gridextra=2.3
  - r-egg=0.4
