channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - snakemake=7
  - biopython>=1.76,<=1.84
  - blast>=2.9,<=2.16
  - r-base=4
  - r-codetools
  - r-conflicted
  - r-getopt=1.20
  - r-argparser=0.7
  - r-futile.logger=1.4
  - r-glue=1
  - r-plyr=1.8
  - r-dplyr=1.1
  - r-tibble=3.2
  - r-reshape2=1.4
  - r-rcolorbrewer=1.1_3
  - r-ggplot2=3.5
  - r-ape=5.8
  - r-maps=3.4
  - r-phytools=2
  - r-tidytree=0.4
  - bioconductor-treeio=1.26
  - bioconductor-ggtree=3.10
  - r-gridextra=2.3
  - r-egg=0.4
